function sigObj = loadSignalObj(filename)
% load and output a signal object from a previously-saved sigObj.mat file.
% If filename/filepath is specified as input, this is used. 
% Otherwise, dialog appears for file selection. 

if nargin < 1
    [fn, fp] = uigetfile('*sigObj.mat');
    filename = [fp,fn];
end

load(filename);


         sigObj = buildSignalObj(Data_Ground_Truth, ...
                                 Data_Unfiltered, Times, Noise_Reference, ...
                                 SampleRate, Channels, ...
                                 Train_Time_Bounds, Preview_Time_Bounds, Preview_Channel_Index, ... Analyze_Time_Bounds, ...
                                 Data_HPF, Data_LMS, Data_LMS_LPF, Data_BPF, ...
                                 Times_Train, Times_Test, Noise_Reference_Train, Noise_Reference_Test, ...
                                 Data_Unfiltered_Train, Data_Unfiltered_Test, ...
                                 Data_HPF_Train, Data_HPF_Test, Data_LMS_Train, Data_LMS_Test, ...
                                 Data_LMS_LPF_Train, Data_LMS_LPF_Test, Data_BPF_Train, Data_BPF_Test);

end